### ISSUE TITLE
Application configuration

### ISSUE THREAD

**Issue by groyoh** [groyoh/minimalin#20]
The application should have a configuration to allow user to:
- [x] Hour hand color
- [x] Minute hand color
- [x] Use rainbow minute hand (Overrides selected color)
- [x] Background color
- [x] Show date
- [x] Date color
- [x] Numbers/ticks color
- [x] When Bluetooth is disconnected, show: No icon - Bluetooth - Broken heart

**Comment by AlessioLaiso** [comment]
We could rephrase the text labels to:

• Hour hand color
• Minute hand color
• Use light theme
• Show date
• Show Bluetooth disconnected icon

**Comment by groyoh** [comment]
![](https://media.giphy.com/media/11sG4llQDAipGw/giphy.gif)
