### ISSUE TITLE
Add a complete description to the README

### ISSUE THREAD

**Issue by groyoh** [groyoh/minimalin#51]
We should add a watchface description in the README which would be the content that we plan to use when publish the watchface.

**Comment by AlessioLaiso** [comment]
The description for the store should be slightly different than the one we'll use for the README.
For the store:

Minimalin is a fully customizable watchface that blends analog and digital for a modern and elegant look.
Minimalin is an open source project. If you love it as much as we do, feel free to tap the HEART and email comments/feedback! :)

• Fully configurable colors
• Date display
• Weather conditions and temperature
• Bluetooth disconnected icon (pick your favorite)
• Rainbow hand, and more great and fun features to come!
