### ISSUE TITLE
Weather/date can be obscured by hands

### ISSUE THREAD

**Issue by SarenCurrie** [groyoh/minimalin#68]
It can be hard to see the weather info at around 12 o'clock (and I assume the date at around 6:30 as well). 
![img_0376](https://cloud.githubusercontent.com/assets/8222891/14446183/5b9d99b0-00a7-11e6-991a-37c03c7067b0.jpg)

**Comment by AlessioLaiso** [comment]
Thanks Saren. We were discussing the idea of moving date and weather according to the position of the hands in a future update, so we hope to solve this in a future update. If you have other ideas let us know!

**Comment by AlessioLaiso** [comment]
As discussed with @groyoh:

**Visibility rank of additional data areas based on portions hidden by the hands** (now that's a mouthful!)
N,N:S,E,W,N
S,N:E,W,S,N
S,S:E,W,N,S
W,N:E,S,W,N
W,S:N,E,S,W
W,W:S,N,E,W
E,E:S,N,W,E
E,S:N,W,S,E
E,W:S,N,E,W
E,E:S,N,W,E

**Comment by stefanheule** [comment]
Hi guys, I just wanted to let you know that I've released a new version of [Obsidian](https://github.com/stefanheule/obsidian) that supports weather information and moves the date out of the way so it's never obscured.  It's available under the Apache License, so feel free to use the code if it seems useful.
Great watch face, by the way! I re-used some of the icons for Obsidian.
