### ISSUE TITLE
Add vibration on Bluetooth disconnect

### ISSUE THREAD

**Issue by DonOregano** [groyoh/minimalin#70]
I really like watchfaces that have this feature built in (yes, I know it's possible to add yourself with that online tool, but I prefer it built in.)

**Comment by groyoh** [comment]
Thanks for the idea.

> yes, I know it's possible to add yourself with that online tool

What do you mean by that?

**Comment by DonOregano** [comment]
You can use this "pebble app remixer" to add features to existing watchfaces:
http://sand.cpfx.ca/

**Comment by groyoh** [comment]
@DonOregano we're gonna put a new update soon and we decided that we won't be adding this feature sorry.
