### ISSUE TITLE
Config page : theme presets option

### ISSUE THREAD

**Issue by marcteys** [groyoh/minimalin#73]
Hi all,

I will work on the config page, adding the theme "presets" to the app. I think it's a really important feature, that has made the success of many other pebble apps. 

The important things :
- By default, the tab should show the themes presets. Don't forget that the user is not a designer 
- Some important features might be display if it's custom  or manual mode.

Here are two really quick design that I propose ; If you have other ideas, you're welcome ! 
## Design 1 :

![design1](https://cloud.githubusercontent.com/assets/5422174/14509448/a8a358be-01cc-11e6-8e40-da55924fd0ce.png)
### Pros / cons
- More beautiful , we can display as many theme as we want
- Horizontal slider might be not user friendly on mobile (we need to test)
## Design 2 :

![design2](https://cloud.githubusercontent.com/assets/5422174/14509449/a8a4aa98-01cc-11e6-9fc6-ea5ff667cc8b.png)
### Pros / cons
- Sure that it will fit on any mobiles
- Works well if we have few themes, more than 10 themes will be too complicated

**Comment by AlessioLaiso** [comment]
Hi Marc, Alessio here, designer of Minimalin. It’s nice to see how involved you are and we’re really happy you’re enjoying our watchface. We discussed the idea of themes some time ago, whether that means having some prebuilt themes (as you’re suggesting) or having some _slots_ to save personal themes for quicker customization.

Your suggestions are valid, but I would rather go for a softer approach, that doesn’t completely hide the finer settings under a segmented control. I also believe having such big previews kind of defeats the purpose of the main big preview on top of the screen. An alternative approach I would suggest is allowing the user to quickly tap through the presets and having the main preview updating.

**Comment by marcteys** [comment]
I think having prebuilt themes make more sense. Once the app is install, the user will be able to select between few designs. 
I had the same idea, when click on a thumbnail it changes the main design. (Maybe on my first mockup the designs are too big). I have made this setting page a while ago : http://half4.com/cabble/cabble.php, using more "minimal" thumbnails. I don't think it's applicable for this app. 

For "Theme / Manual", I am just considering the color choices. All the other settings have to remain here. Doesn't make sens to display themes & color choices at the same time, imho. 

PS : That's the kind of watchface I always wanted to made but never add enough time ^^ I want to improve the settings page because some features I need are missing, so if I want to do it, I do it & share .  :p
