### ISSUE TITLE
Adding step count and distance walked as options to display on the watchface

### ISSUE THREAD

**Issue by rezart** [groyoh/minimalin#75]
Not totally sure where on the watchface they should go on but thinking about one or multiple of the corners depending on how many pieces of health data we want to support at the same time.

**Comment by rezart** [comment]
@groyoh ah I see that you already referenced this in #69. We could use this issue to discuss it in more detail if other folks are interested.

**Comment by groyoh** [comment]
Steps are on the way. I already experimented quickly with the steps and battery level. The complex part is to fit that with #68.

About the distance walked I'm not sure though as it may be too much on the screen. Our goal is still to keep it minimal.

**Comment by rezart** [comment]
Agreed about keeping it minimal. Could be cool if we supported both options and the user could pick which one to display.
