### ISSUE TITLE
Pebble Health nag screen with Health disabled

### ISSUE THREAD

**Issue by timothythlau** [groyoh/minimalin#77]
Nag screen with occasionally pop up with this watchface. I have the Health features turned off on my watch, as I do not have the watch on 24/7. Had the same issue with another watchface, required some dev changes to remove access to the Heath features to resolve.

**Comment by groyoh** [comment]
@timothythlau do you have or can you point me to any  solution for that?

**Comment by timothythlau** [comment]
I have a feeling it has something to do with this function:

```
static void tick_handler(struct tm *tick_time, TimeUnits units_changed){
  if(HOUR_UNIT & units_changed){
    HealthActivity activity = health_service_peek_current_activities();
    if(activity == HealthActivityNone){
```

Looks like the tick handler for vibrating every hour will use the Pebble Health API to check if the user is sleeping or not. Would probably require a check if health capabilities are enabled or not before actually querying the API.

**Comment by groyoh** [comment]
@timothythlau sorry about the (extremely) late reply but I had a break from coding for some time. Your PR is merged but I don't know if it will solve the issue though.
