### ISSUE TITLE
Dark Sky for Weather? 

### ISSUE THREAD

**Issue by maxmoseley23** [groyoh/minimalin#81]
OpenWeatherMap is good but is the least accurate out of the big 3 (Wu, Dark Sky, OWM).

Is this something we can see in the future? To replace OWM or even implement MasterKey for multiple provider coverage.

**Comment by groyoh** [comment]
AFAIK both WU and Dark Sky only have paid plans (even for Open Source open projects). Also we do not want to offer users the possibility to use their own API keys as this would bloat the config page even more. So I'm sorry but I guess we won't change it. 

Have you been having some issues with the weather accuracy while using minimalin?

**Comment by maxmoseley23** [comment]
I understand about the config page bloat. 

It's just that Dark Sky is wicked accurate in my area. But to anyone interested, here's a patch that replaces OWM with Dark Sky.
[dark-sky.patch.txt](https://github.com/groyoh/minimalin/files/573220/dark-sky.patch.txt)

**Comment by groyoh** [comment]
@maxmoseley23 their free plans have very limited usage. Sorry for the inconvenience.
